# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-07 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_type', models.BooleanField(verbose_name=b'Offence')),
                ('charge_kind', models.CharField(max_length=30, verbose_name=b'Charge nature')),
                ('charge', models.CharField(max_length=100, verbose_name=b'Charges')),
                ('loc_lat', models.FloatField(verbose_name=b'Latitude')),
                ('loc_long', models.FloatField(verbose_name=b'Longitude')),
                ('when', models.DateTimeField(verbose_name=b'Date of Charge')),
            ],
        ),
        migrations.CreateModel(
            name='Missing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(verbose_name=b'Date of Filing Report')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.BooleanField(verbose_name=b'Offence')),
                ('payment_mode', models.CharField(max_length=20, verbose_name=b'Mode of Payment')),
                ('when', models.DateTimeField(verbose_name=b'Date of Payment')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('veh_number', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name=b'Number Plate of Vehicle')),
                ('veh_color', models.CharField(max_length=10, verbose_name=b'Color of Vehicle')),
                ('veh_type', models.CharField(max_length=10, verbose_name=b'Type of Vehicle')),
                ('veh_make', models.CharField(max_length=30, verbose_name=b'Make of Vehicle')),
                ('owner_id', models.IntegerField(verbose_name=b'Identification of Owner')),
                ('charges_due', models.IntegerField(default=0, verbose_name=b'Charges Dues')),
                ('penalty', models.IntegerField(default=0, verbose_name=b'Penalty Dues')),
                ('lastcrossing_lat', models.FloatField(default=-1.0, verbose_name=b'Last seen latitude')),
                ('lastcrossing_long', models.FloatField(default=-1.0, verbose_name=b'Last seen longitude')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='veh_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trafficontrol.Vehicle'),
        ),
        migrations.AddField(
            model_name='missing',
            name='veh_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trafficontrol.Vehicle'),
        ),
        migrations.AddField(
            model_name='charges',
            name='veh_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trafficontrol.Vehicle'),
        ),
    ]
